<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        if (!Country::first()) {
            Country::insert(
                [
                    [
                        'name' => 'South Georgia',
                        'pl_name' => 'Georgia Południowa i Sandwich Południowy',
                        'code' => 'GS',
                        'currency' => 'Saint Helena pound',
                        'currency_symbol' => '£',
                        'currency_code' => 'SHP',
                    ],
                    [
                        'name' => 'Grenada',
                        'pl_name' => 'Grenada',
                        'code' => 'GD',
                        'currency' => 'Eastern Caribbean dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'XCD',
                    ],
                    [
                        'name' => 'Switzerland',
                        'pl_name' => 'Szwajcaria',
                        'code' => 'CH',
                        'currency' => 'Swiss franc',
                        'currency_symbol' => 'Fr.',
                        'currency_code' => 'CHF',
                    ],
                    [
                        'name' => 'Sierra Leone',
                        'pl_name' => 'Sierra Leone',
                        'code' => 'SL',
                        'currency' => 'Sierra Leonean leone',
                        'currency_symbol' => 'Le',
                        'currency_code' => 'SLL',
                    ],
                    [
                        'name' => 'Hungary',
                        'pl_name' => 'Węgry',
                        'code' => 'HU',
                        'currency' => 'Hungarian forint',
                        'currency_symbol' => 'Ft',
                        'currency_code' => 'HUF',
                    ],
                    [
                        'name' => 'Taiwan',
                        'pl_name' => 'Tajwan',
                        'code' => 'TW',
                        'currency' => 'New Taiwan dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'TWD',
                    ],
                    [
                        'name' => 'Wallis and Futuna',
                        'pl_name' => 'Wallis i Futuna',
                        'code' => 'WF',
                        'currency' => 'CFP franc',
                        'currency_symbol' => '₣',
                        'currency_code' => 'XPF',
                    ],
                    [
                        'name' => 'Barbados',
                        'pl_name' => 'Barbados',
                        'code' => 'BB',
                        'currency' => 'Barbadian dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'BBD',
                    ],
                    [
                        'name' => 'Pitcairn Islands',
                        'pl_name' => 'Pitcairn',
                        'code' => 'PN',
                        'currency' => 'New Zealand dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'NZD',
                    ],
                    [
                        'name' => 'Ivory Coast',
                        'pl_name' => 'WybrzeŻe Kości Słoniowej',
                        'code' => 'CI',
                        'currency' => 'West African CFA franc',
                        'currency_symbol' => 'Fr',
                        'currency_code' => 'XOF',
                    ],
                    [
                        'name' => 'Tunisia',
                        'pl_name' => 'Tunezja',
                        'code' => 'TN',
                        'currency' => 'Tunisian dinar',
                        'currency_symbol' => 'د.ت',
                        'currency_code' => 'TND',
                    ],
                    [
                        'name' => 'Italy',
                        'pl_name' => 'Włochy',
                        'code' => 'IT',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Benin',
                        'pl_name' => 'Benin',
                        'code' => 'BJ',
                        'currency' => 'West African CFA franc',
                        'currency_symbol' => 'Fr',
                        'currency_code' => 'XOF',
                    ],
                    [
                        'name' => 'Indonesia',
                        'pl_name' => 'Indonezja',
                        'code' => 'ID',
                        'currency' => 'Indonesian rupiah',
                        'currency_symbol' => 'Rp',
                        'currency_code' => 'IDR',
                    ],
                    [
                        'name' => 'Cape Verde',
                        'pl_name' => 'Republika Zielonego Przylądka',
                        'code' => 'CV',
                        'currency' => 'Cape Verdean escudo',
                        'currency_symbol' => 'Esc',
                        'currency_code' => 'CVE',
                    ],
                    [
                        'name' => 'Saint Kitts and Nevis',
                        'pl_name' => 'Saint Kitts i Nevis',
                        'code' => 'KN',
                        'currency' => 'Eastern Caribbean dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'XCD',
                    ],
                    [
                        'name' => 'Laos',
                        'pl_name' => 'Laos',
                        'code' => 'LA',
                        'currency' => 'Lao kip',
                        'currency_symbol' => '₭',
                        'currency_code' => 'LAK',
                    ],
                    [
                        'name' => 'Caribbean Netherlands',
                        'pl_name' => 'Antyle Holenderskie',
                        'code' => 'BQ',
                        'currency' => 'United States dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'USD',
                    ],
                    [
                        'name' => 'Uganda',
                        'pl_name' => 'Uganda',
                        'code' => 'UG',
                        'currency' => 'Ugandan shilling',
                        'currency_symbol' => 'Sh',
                        'currency_code' => 'UGX',
                    ],
                    [
                        'name' => 'Andorra',
                        'pl_name' => 'Andora',
                        'code' => 'AD',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Burundi',
                        'pl_name' => 'Burundi',
                        'code' => 'BI',
                        'currency' => 'Burundian franc',
                        'currency_symbol' => 'Fr',
                        'currency_code' => 'BIF',
                    ],
                    [
                        'name' => 'South Africa',
                        'pl_name' => 'Południowa Afryka',
                        'code' => 'ZA',
                        'currency' => 'South African rand',
                        'currency_symbol' => 'R',
                        'currency_code' => 'ZAR',
                    ],
                    [
                        'name' => 'France',
                        'pl_name' => 'Francja',
                        'code' => 'FR',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Libya',
                        'pl_name' => 'Libia',
                        'code' => 'LY',
                        'currency' => 'Libyan dinar',
                        'currency_symbol' => 'ل.د',
                        'currency_code' => 'LYD',
                    ],
                    [
                        'name' => 'Mexico',
                        'pl_name' => 'Meksyk',
                        'code' => 'MX',
                        'currency' => 'Mexican peso',
                        'currency_symbol' => '$',
                        'currency_code' => 'MXN',
                    ],
                    [
                        'name' => 'Gabon',
                        'pl_name' => 'Gabon',
                        'code' => 'GA',
                        'currency' => 'Central African CFA franc',
                        'currency_symbol' => 'Fr',
                        'currency_code' => 'XAF',
                    ],
                    [
                        'name' => 'Northern Mariana Islands',
                        'pl_name' => 'Mariany Północne',
                        'code' => 'MP',
                        'currency' => 'United States dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'USD',
                    ],
                    [
                        'name' => 'North Macedonia',
                        'pl_name' => 'Macedonia Północna',
                        'code' => 'MK',
                        'currency' => 'denar',
                        'currency_symbol' => 'den',
                        'currency_code' => 'MKD',
                    ],
                    [
                        'name' => 'China',
                        'pl_name' => 'Chiny',
                        'code' => 'CN',
                        'currency' => 'Chinese yuan',
                        'currency_symbol' => '¥',
                        'currency_code' => 'CNY',
                    ],
                    [
                        'name' => 'Yemen',
                        'pl_name' => 'Jemen',
                        'code' => 'YE',
                        'currency' => 'Yemeni rial',
                        'currency_symbol' => '﷼',
                        'currency_code' => 'YER',
                    ],
                    [
                        'name' => 'Saint Barthélemy',
                        'pl_name' => 'Saint-Barthélemy',
                        'code' => 'BL',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Guernsey',
                        'pl_name' => 'Guernsey',
                        'code' => 'GG',
                        'currency' => 'British pound',
                        'currency_symbol' => '£',
                        'currency_code' => 'GBP',
                    ],
                    [
                        'name' => 'Solomon Islands',
                        'pl_name' => 'Wyspy Salomona',
                        'code' => 'SB',
                        'currency' => 'Solomon Islands dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'SBD',
                    ],
                    [
                        'name' => 'Svalbard and Jan Mayen',
                        'pl_name' => 'Svalbard i Jan Mayen',
                        'code' => 'SJ',
                        'currency' => 'krone',
                        'currency_symbol' => 'kr',
                        'currency_code' => 'NOK',
                    ],
                    [
                        'name' => 'Faroe Islands',
                        'pl_name' => 'Wyspy Owcze',
                        'code' => 'FO',
                        'currency' => 'Danish krone',
                        'currency_symbol' => 'kr',
                        'currency_code' => 'DKK',
                    ],
                    [
                        'name' => 'Uzbekistan',
                        'pl_name' => 'Uzbekistan',
                        'code' => 'UZ',
                        'currency' => 'Uzbekistani soʻm',
                        'currency_symbol' => 'so\'m',
                        'currency_code' => 'UZS',
                    ],
                    [
                        'name' => 'Egypt',
                        'pl_name' => 'Egipt',
                        'code' => 'EG',
                        'currency' => 'Egyptian pound',
                        'currency_symbol' => '£',
                        'currency_code' => 'EGP',
                    ],
                    [
                        'name' => 'Senegal',
                        'pl_name' => 'Senegal',
                        'code' => 'SN',
                        'currency' => 'West African CFA franc',
                        'currency_symbol' => 'Fr',
                        'currency_code' => 'XOF',
                    ],
                    [
                        'name' => 'Sri Lanka',
                        'pl_name' => 'Sri Lanka',
                        'code' => 'LK',
                        'currency' => 'Sri Lankan rupee',
                        'currency_symbol' => 'Rs  රු',
                        'currency_code' => 'LKR',
                    ],
                    [
                        'name' => 'Palestine',
                        'pl_name' => 'Palestyna',
                        'code' => 'PS',
                        'currency' => 'Egyptian pound',
                        'currency_symbol' => 'E£',
                        'currency_code' => 'EGP',
                    ],
                    [
                        'name' => 'Bangladesh',
                        'pl_name' => 'Bangladesz',
                        'code' => 'BD',
                        'currency' => 'Bangladeshi taka',
                        'currency_symbol' => '৳',
                        'currency_code' => 'BDT',
                    ],
                    [
                        'name' => 'Peru',
                        'pl_name' => 'Peru',
                        'code' => 'PE',
                        'currency' => 'Peruvian sol',
                        'currency_symbol' => 'S/ ',
                        'currency_code' => 'PEN',
                    ],
                    [
                        'name' => 'Singapore',
                        'pl_name' => 'Singapur',
                        'code' => 'SG',
                        'currency' => 'Singapore dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'SGD',
                    ],
                    [
                        'name' => 'Turkey',
                        'pl_name' => 'Turcja',
                        'code' => 'TR',
                        'currency' => 'Turkish lira',
                        'currency_symbol' => '₺',
                        'currency_code' => 'TRY',
                    ],
                    [
                        'name' => 'Afghanistan',
                        'pl_name' => 'Afganistan',
                        'code' => 'AF',
                        'currency' => 'Afghan afghani',
                        'currency_symbol' => '؋',
                        'currency_code' => 'AFN',
                    ],
                    [
                        'name' => 'Aruba',
                        'pl_name' => 'Aruba',
                        'code' => 'AW',
                        'currency' => 'Aruban florin',
                        'currency_symbol' => 'ƒ',
                        'currency_code' => 'AWG',
                    ],
                    [
                        'name' => 'Cook Islands',
                        'pl_name' => 'Wyspy Cooka',
                        'code' => 'CK',
                        'currency' => 'Cook Islands dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'CKD',
                    ],
                    [
                        'name' => 'United Kingdom',
                        'pl_name' => 'Zjednoczone Królestwo',
                        'code' => 'GB',
                        'currency' => 'British pound',
                        'currency_symbol' => '£',
                        'currency_code' => 'GBP',
                    ],
                    [
                        'name' => 'Zambia',
                        'pl_name' => 'Zambia',
                        'code' => 'ZM',
                        'currency' => 'Zambian kwacha',
                        'currency_symbol' => 'ZK',
                        'currency_code' => 'ZMW',
                    ],
                    [
                        'name' => 'Finland',
                        'pl_name' => 'Finlandia',
                        'code' => 'FI',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Niger',
                        'pl_name' => 'Niger',
                        'code' => 'NE',
                        'currency' => 'West African CFA franc',
                        'currency_symbol' => 'Fr',
                        'currency_code' => 'XOF',
                    ],
                    [
                        'name' => 'Christmas Island',
                        'pl_name' => 'Wyspa Bożego Narodzenia',
                        'code' => 'CX',
                        'currency' => 'Australian dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'AUD',
                    ],
                    [
                        'name' => 'Tokelau',
                        'pl_name' => 'Tokelau',
                        'code' => 'TK',
                        'currency' => 'New Zealand dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'NZD',
                    ],
                    [
                        'name' => 'Guinea-Bissau',
                        'pl_name' => 'Gwinea Bissau',
                        'code' => 'GW',
                        'currency' => 'West African CFA franc',
                        'currency_symbol' => 'Fr',
                        'currency_code' => 'XOF',
                    ],
                    [
                        'name' => 'Azerbaijan',
                        'pl_name' => 'Azerbejdżan',
                        'code' => 'AZ',
                        'currency' => 'Azerbaijani manat',
                        'currency_symbol' => '₼',
                        'currency_code' => 'AZN',
                    ],
                    [
                        'name' => 'Réunion',
                        'pl_name' => 'Reunion',
                        'code' => 'RE',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Djibouti',
                        'pl_name' => 'Dżibuti',
                        'code' => 'DJ',
                        'currency' => 'Djiboutian franc',
                        'currency_symbol' => 'Fr',
                        'currency_code' => 'DJF',
                    ],
                    [
                        'name' => 'North Korea',
                        'pl_name' => 'Korea Północna',
                        'code' => 'KP',
                        'currency' => 'North Korean won',
                        'currency_symbol' => '₩',
                        'currency_code' => 'KPW',
                    ],
                    [
                        'name' => 'Mauritius',
                        'pl_name' => 'Mauritius',
                        'code' => 'MU',
                        'currency' => 'Mauritian rupee',
                        'currency_symbol' => '₨',
                        'currency_code' => 'MUR',
                    ],
                    [
                        'name' => 'Montserrat',
                        'pl_name' => 'Montserrat',
                        'code' => 'MS',
                        'currency' => 'Eastern Caribbean dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'XCD',
                    ],
                    [
                        'name' => 'United States Virgin Islands',
                        'pl_name' => 'Wyspy Dziewicze Stanów Zjednoczonych',
                        'code' => 'VI',
                        'currency' => 'United States dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'USD',
                    ],
                    [
                        'name' => 'Colombia',
                        'pl_name' => 'Kolumbia',
                        'code' => 'CO',
                        'currency' => 'Colombian peso',
                        'currency_symbol' => '$',
                        'currency_code' => 'COP',
                    ],
                    [
                        'name' => 'Greece',
                        'pl_name' => 'Grecja',
                        'code' => 'GR',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Croatia',
                        'pl_name' => 'Chorwacja',
                        'code' => 'HR',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Morocco',
                        'pl_name' => 'Maroko',
                        'code' => 'MA',
                        'currency' => 'Moroccan dirham',
                        'currency_symbol' => 'د.م.',
                        'currency_code' => 'MAD',
                    ],
                    [
                        'name' => 'Algeria',
                        'pl_name' => 'Algieria',
                        'code' => 'DZ',
                        'currency' => 'Algerian dinar',
                        'currency_symbol' => 'د.ج',
                        'currency_code' => 'DZD',
                    ],
                    [
                        'name' => 'Netherlands',
                        'pl_name' => 'Holandia',
                        'code' => 'NL',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Sudan',
                        'pl_name' => 'Sudan',
                        'code' => 'SD',
                        'currency' => 'Sudanese pound',
                        'currency_symbol' => 'ج.س',
                        'currency_code' => 'SDG',
                    ],
                    [
                        'name' => 'Fiji',
                        'pl_name' => 'Fidżi',
                        'code' => 'FJ',
                        'currency' => 'Fijian dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'FJD',
                    ],
                    [
                        'name' => 'Liechtenstein',
                        'pl_name' => 'Liechtenstein',
                        'code' => 'LI',
                        'currency' => 'Swiss franc',
                        'currency_symbol' => 'Fr',
                        'currency_code' => 'CHF',
                    ],
                    [
                        'name' => 'Nepal',
                        'pl_name' => 'Nepal',
                        'code' => 'NP',
                        'currency' => 'Nepalese rupee',
                        'currency_symbol' => '₨',
                        'currency_code' => 'NPR',
                    ],
                    [
                        'name' => 'Puerto Rico',
                        'pl_name' => 'Portoryko',
                        'code' => 'PR',
                        'currency' => 'United States dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'USD',
                    ],
                    [
                        'name' => 'Georgia',
                        'pl_name' => 'Gruzja',
                        'code' => 'GE',
                        'currency' => 'lari',
                        'currency_symbol' => '₾',
                        'currency_code' => 'GEL',
                    ],
                    [
                        'name' => 'Pakistan',
                        'pl_name' => 'Pakistan',
                        'code' => 'PK',
                        'currency' => 'Pakistani rupee',
                        'currency_symbol' => '₨',
                        'currency_code' => 'PKR',
                    ],
                    [
                        'name' => 'Monaco',
                        'pl_name' => 'Monako',
                        'code' => 'MC',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Botswana',
                        'pl_name' => 'Botswana',
                        'code' => 'BW',
                        'currency' => 'Botswana pula',
                        'currency_symbol' => 'P',
                        'currency_code' => 'BWP',
                    ],
                    [
                        'name' => 'Lebanon',
                        'pl_name' => 'Liban',
                        'code' => 'LB',
                        'currency' => 'Lebanese pound',
                        'currency_symbol' => 'ل.ل',
                        'currency_code' => 'LBP',
                    ],
                    [
                        'name' => 'Papua New Guinea',
                        'pl_name' => 'Papua-Nowa Gwinea',
                        'code' => 'PG',
                        'currency' => 'Papua New Guinean kina',
                        'currency_symbol' => 'K',
                        'currency_code' => 'PGK',
                    ],
                    [
                        'name' => 'Mayotte',
                        'pl_name' => 'Majotta',
                        'code' => 'YT',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Dominican Republic',
                        'pl_name' => 'Dominikana',
                        'code' => 'DO',
                        'currency' => 'Dominican peso',
                        'currency_symbol' => '$',
                        'currency_code' => 'DOP',
                    ],
                    [
                        'name' => 'Norfolk Island',
                        'pl_name' => 'Wyspa Norfolk',
                        'code' => 'NF',
                        'currency' => 'Australian dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'AUD',
                    ],
                    [
                        'name' => 'Qatar',
                        'pl_name' => 'Katar',
                        'code' => 'QA',
                        'currency' => 'Qatari riyal',
                        'currency_symbol' => 'ر.ق',
                        'currency_code' => 'QAR',
                    ],
                    [
                        'name' => 'Madagascar',
                        'pl_name' => 'Madagaskar',
                        'code' => 'MG',
                        'currency' => 'Malagasy ariary',
                        'currency_symbol' => 'Ar',
                        'currency_code' => 'MGA',
                    ],
                    [
                        'name' => 'India',
                        'pl_name' => 'Indie',
                        'code' => 'IN',
                        'currency' => 'Indian rupee',
                        'currency_symbol' => '₹',
                        'currency_code' => 'INR',
                    ],
                    [
                        'name' => 'Syria',
                        'pl_name' => 'Syria',
                        'code' => 'SY',
                        'currency' => 'Syrian pound',
                        'currency_symbol' => '£',
                        'currency_code' => 'SYP',
                    ],
                    [
                        'name' => 'Montenegro',
                        'pl_name' => 'Czarnogóra',
                        'code' => 'ME',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Eswatini',
                        'pl_name' => 'Suazi',
                        'code' => 'SZ',
                        'currency' => 'Swazi lilangeni',
                        'currency_symbol' => 'L',
                        'currency_code' => 'SZL',
                    ],
                    [
                        'name' => 'Paraguay',
                        'pl_name' => 'Paragwaj',
                        'code' => 'PY',
                        'currency' => 'Paraguayan guaraní',
                        'currency_symbol' => '₲',
                        'currency_code' => 'PYG',
                    ],
                    [
                        'name' => 'El Salvador',
                        'pl_name' => 'Salwador',
                        'code' => 'SV',
                        'currency' => 'United States dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'USD',
                    ],
                    [
                        'name' => 'Ukraine',
                        'pl_name' => 'Ukraina',
                        'code' => 'UA',
                        'currency' => 'Ukrainian hryvnia',
                        'currency_symbol' => '₴',
                        'currency_code' => 'UAH',
                    ],
                    [
                        'name' => 'Isle of Man',
                        'pl_name' => 'Wyspa Man',
                        'code' => 'IM',
                        'currency' => 'British pound',
                        'currency_symbol' => '£',
                        'currency_code' => 'GBP',
                    ],
                    [
                        'name' => 'Namibia',
                        'pl_name' => 'Namibia',
                        'code' => 'NA',
                        'currency' => 'Namibian dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'NAD',
                    ],
                    [
                        'name' => 'United Arab Emirates',
                        'pl_name' => 'Emiraty Arabskie',
                        'code' => 'AE',
                        'currency' => 'United Arab Emirates dirham',
                        'currency_symbol' => 'د.إ',
                        'currency_code' => 'AED',
                    ],
                    [
                        'name' => 'Bulgaria',
                        'pl_name' => 'Bułgaria',
                        'code' => 'BG',
                        'currency' => 'Bulgarian lev',
                        'currency_symbol' => 'лв',
                        'currency_code' => 'BGN',
                    ],
                    [
                        'name' => 'Greenland',
                        'pl_name' => 'Grenlandia',
                        'code' => 'GL',
                        'currency' => 'krone',
                        'currency_symbol' => 'kr.',
                        'currency_code' => 'DKK',
                    ],
                    [
                        'name' => 'Germany',
                        'pl_name' => 'Niemcy',
                        'code' => 'DE',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Cambodia',
                        'pl_name' => 'Kambodża',
                        'code' => 'KH',
                        'currency' => 'Cambodian riel',
                        'currency_symbol' => '៛',
                        'currency_code' => 'KHR',
                    ],
                    [
                        'name' => 'Iraq',
                        'pl_name' => 'Irak',
                        'code' => 'IQ',
                        'currency' => 'Iraqi dinar',
                        'currency_symbol' => 'ع.د',
                        'currency_code' => 'IQD',
                    ],
                    [
                        'name' => 'French Southern and Antarctic Lands',
                        'pl_name' => 'Francuskie Terytoria Południowe i Antarktyczne',
                        'code' => 'TF',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Sweden',
                        'pl_name' => 'Szwecja',
                        'code' => 'SE',
                        'currency' => 'Swedish krona',
                        'currency_symbol' => 'kr',
                        'currency_code' => 'SEK',
                    ],
                    [
                        'name' => 'Cuba',
                        'pl_name' => 'Kuba',
                        'code' => 'CU',
                        'currency' => 'Cuban convertible peso',
                        'currency_symbol' => '$',
                        'currency_code' => 'CUC',
                    ],
                    [
                        'name' => 'Kyrgyzstan',
                        'pl_name' => 'Kirgistan',
                        'code' => 'KG',
                        'currency' => 'Kyrgyzstani som',
                        'currency_symbol' => 'с',
                        'currency_code' => 'KGS',
                    ],
                    [
                        'name' => 'Russia',
                        'pl_name' => 'Rosja',
                        'code' => 'RU',
                        'currency' => 'Russian ruble',
                        'currency_symbol' => '₽',
                        'currency_code' => 'RUB',
                    ],
                    [
                        'name' => 'Malaysia',
                        'pl_name' => 'Malezja',
                        'code' => 'MY',
                        'currency' => 'Malaysian ringgit',
                        'currency_symbol' => 'RM',
                        'currency_code' => 'MYR',
                    ],
                    [
                        'name' => 'São Tomé and Príncipe',
                        'pl_name' => 'Wyspy Świętego Tomasza i Książęca',
                        'code' => 'ST',
                        'currency' => 'São Tomé and Príncipe dobra',
                        'currency_symbol' => 'Db',
                        'currency_code' => 'STN',
                    ],
                    [
                        'name' => 'Cyprus',
                        'pl_name' => 'Cypr',
                        'code' => 'CY',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Canada',
                        'pl_name' => 'Kanada',
                        'code' => 'CA',
                        'currency' => 'Canadian dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'CAD',
                    ],
                    [
                        'name' => 'Malawi',
                        'pl_name' => 'Malawi',
                        'code' => 'MW',
                        'currency' => 'Malawian kwacha',
                        'currency_symbol' => 'MK',
                        'currency_code' => 'MWK',
                    ],
                    [
                        'name' => 'Saudi Arabia',
                        'pl_name' => 'Arabia Saudyjska',
                        'code' => 'SA',
                        'currency' => 'Saudi riyal',
                        'currency_symbol' => 'ر.س',
                        'currency_code' => 'SAR',
                    ],
                    [
                        'name' => 'Bosnia and Herzegovina',
                        'pl_name' => 'Bośnia i Hercegowina',
                        'code' => 'BA',
                        'currency' => 'Bosnia and Herzegovina convertible mark',
                        'currency_symbol' => 'KM',
                        'currency_code' => 'BAM',
                    ],
                    [
                        'name' => 'Ethiopia',
                        'pl_name' => 'Etiopia',
                        'code' => 'ET',
                        'currency' => 'Ethiopian birr',
                        'currency_symbol' => 'Br',
                        'currency_code' => 'ETB',
                    ],
                    [
                        'name' => 'Spain',
                        'pl_name' => 'Hiszpania',
                        'code' => 'ES',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Slovenia',
                        'pl_name' => 'Słowenia',
                        'code' => 'SI',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Oman',
                        'pl_name' => 'Oman',
                        'code' => 'OM',
                        'currency' => 'Omani rial',
                        'currency_symbol' => 'ر.ع.',
                        'currency_code' => 'OMR',
                    ],
                    [
                        'name' => 'Saint Pierre and Miquelon',
                        'pl_name' => 'Saint-Pierre i Miquelon',
                        'code' => 'PM',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Macau',
                        'pl_name' => 'Makau',
                        'code' => 'MO',
                        'currency' => 'Macanese pataca',
                        'currency_symbol' => 'P',
                        'currency_code' => 'MOP',
                    ],
                    [
                        'name' => 'San Marino',
                        'pl_name' => 'San Marino',
                        'code' => 'SM',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Lesotho',
                        'pl_name' => 'Lesotho',
                        'code' => 'LS',
                        'currency' => 'Lesotho loti',
                        'currency_symbol' => 'L',
                        'currency_code' => 'LSL',
                    ],
                    [
                        'name' => 'Marshall Islands',
                        'pl_name' => 'Wyspy Marshalla',
                        'code' => 'MH',
                        'currency' => 'United States dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'USD',
                    ],
                    [
                        'name' => 'Sint Maarten',
                        'pl_name' => 'Sint Maarten',
                        'code' => 'SX',
                        'currency' => 'Netherlands Antillean guilder',
                        'currency_symbol' => 'ƒ',
                        'currency_code' => 'ANG',
                    ],
                    [
                        'name' => 'Iceland',
                        'pl_name' => 'Islandia',
                        'code' => 'IS',
                        'currency' => 'Icelandic króna',
                        'currency_symbol' => 'kr',
                        'currency_code' => 'ISK',
                    ],
                    [
                        'name' => 'Luxembourg',
                        'pl_name' => 'Luksemburg',
                        'code' => 'LU',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Argentina',
                        'pl_name' => 'Argentyna',
                        'code' => 'AR',
                        'currency' => 'Argentine peso',
                        'currency_symbol' => '$',
                        'currency_code' => 'ARS',
                    ],
                    [
                        'name' => 'Turks and Caicos Islands',
                        'pl_name' => 'Turks i Caicos',
                        'code' => 'TC',
                        'currency' => 'United States dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'USD',
                    ],
                    [
                        'name' => 'Nauru',
                        'pl_name' => 'Nauru',
                        'code' => 'NR',
                        'currency' => 'Australian dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'AUD',
                    ],
                    [
                        'name' => 'Cocos (Keeling] Islands',
                        'pl_name' => 'Wyspy Kokosowe',
                        'code' => 'CC',
                        'currency' => 'Australian dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'AUD',
                    ],
                    [
                        'name' => 'Western Sahara',
                        'pl_name' => 'Sahara Zachodnia',
                        'code' => 'EH',
                        'currency' => 'Algerian dinar',
                        'currency_symbol' => 'دج',
                        'currency_code' => 'DZD',
                    ],
                    [
                        'name' => 'Dominica',
                        'pl_name' => 'Dominika',
                        'code' => 'DM',
                        'currency' => 'Eastern Caribbean dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'XCD',
                    ],
                    [
                        'name' => 'Costa Rica',
                        'pl_name' => 'Kostaryka',
                        'code' => 'CR',
                        'currency' => 'Costa Rican colón',
                        'currency_symbol' => '₡',
                        'currency_code' => 'CRC',
                    ],
                    [
                        'name' => 'Australia',
                        'pl_name' => 'Australia',
                        'code' => 'AU',
                        'currency' => 'Australian dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'AUD',
                    ],
                    [
                        'name' => 'Thailand',
                        'pl_name' => 'Tajlandia',
                        'code' => 'TH',
                        'currency' => 'Thai baht',
                        'currency_symbol' => '฿',
                        'currency_code' => 'THB',
                    ],
                    [
                        'name' => 'Haiti',
                        'pl_name' => 'Haiti',
                        'code' => 'HT',
                        'currency' => 'Haitian gourde',
                        'currency_symbol' => 'G',
                        'currency_code' => 'HTG',
                    ],
                    [
                        'name' => 'Tuvalu',
                        'pl_name' => 'Tuvalu',
                        'code' => 'TV',
                        'currency' => 'Australian dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'AUD',
                    ],
                    [
                        'name' => 'Honduras',
                        'pl_name' => 'Honduras',
                        'code' => 'HN',
                        'currency' => 'Honduran lempira',
                        'currency_symbol' => 'L',
                        'currency_code' => 'HNL',
                    ],
                    [
                        'name' => 'Equatorial Guinea',
                        'pl_name' => 'Gwinea Równikowa',
                        'code' => 'GQ',
                        'currency' => 'Central African CFA franc',
                        'currency_symbol' => 'Fr',
                        'currency_code' => 'XAF',
                    ],
                    [
                        'name' => 'Saint Lucia',
                        'pl_name' => 'Saint Lucia',
                        'code' => 'LC',
                        'currency' => 'Eastern Caribbean dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'XCD',
                    ],
                    [
                        'name' => 'French Polynesia',
                        'pl_name' => 'Polinezja Francuska',
                        'code' => 'PF',
                        'currency' => 'CFP franc',
                        'currency_symbol' => '₣',
                        'currency_code' => 'XPF',
                    ],
                    [
                        'name' => 'Belarus',
                        'pl_name' => 'Białoruś',
                        'code' => 'BY',
                        'currency' => 'Belarusian ruble',
                        'currency_symbol' => 'Br',
                        'currency_code' => 'BYN',
                    ],
                    [
                        'name' => 'Latvia',
                        'pl_name' => 'Łotwa',
                        'code' => 'LV',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Palau',
                        'pl_name' => 'Palau',
                        'code' => 'PW',
                        'currency' => 'United States dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'USD',
                    ],
                    [
                        'name' => 'Guadeloupe',
                        'pl_name' => 'Gwadelupa',
                        'code' => 'GP',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Philippines',
                        'pl_name' => 'Filipiny',
                        'code' => 'PH',
                        'currency' => 'Philippine peso',
                        'currency_symbol' => '₱',
                        'currency_code' => 'PHP',
                    ],
                    [
                        'name' => 'Gibraltar',
                        'pl_name' => 'Gibraltar',
                        'code' => 'GI',
                        'currency' => 'Gibraltar pound',
                        'currency_symbol' => '£',
                        'currency_code' => 'GIP',
                    ],
                    [
                        'name' => 'Denmark',
                        'pl_name' => 'Dania',
                        'code' => 'DK',
                        'currency' => 'Danish krone',
                        'currency_symbol' => 'kr',
                        'currency_code' => 'DKK',
                    ],
                    [
                        'name' => 'Cameroon',
                        'pl_name' => 'Kamerun',
                        'code' => 'CM',
                        'currency' => 'Central African CFA franc',
                        'currency_symbol' => 'Fr',
                        'currency_code' => 'XAF',
                    ],
                    [
                        'name' => 'Guinea',
                        'pl_name' => 'Gwinea',
                        'code' => 'GN',
                        'currency' => 'Guinean franc',
                        'currency_symbol' => 'Fr',
                        'currency_code' => 'GNF',
                    ],
                    [
                        'name' => 'Bahrain',
                        'pl_name' => 'Bahrajn',
                        'code' => 'BH',
                        'currency' => 'Bahraini dinar',
                        'currency_symbol' => '.د.ب',
                        'currency_code' => 'BHD',
                    ],
                    [
                        'name' => 'Suriname',
                        'pl_name' => 'Surinam',
                        'code' => 'SR',
                        'currency' => 'Surinamese dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'SRD',
                    ],
                    [
                        'name' => 'DR Congo',
                        'pl_name' => 'Demokratyczna Republika Konga',
                        'code' => 'CD',
                        'currency' => 'Congolese franc',
                        'currency_symbol' => 'FC',
                        'currency_code' => 'CDF',
                    ],
                    [
                        'name' => 'Somalia',
                        'pl_name' => 'Somalia',
                        'code' => 'SO',
                        'currency' => 'Somali shilling',
                        'currency_symbol' => 'Sh',
                        'currency_code' => 'SOS',
                    ],
                    [
                        'name' => 'Czechia',
                        'pl_name' => 'Czechy',
                        'code' => 'CZ',
                        'currency' => 'Czech koruna',
                        'currency_symbol' => 'Kč',
                        'currency_code' => 'CZK',
                    ],
                    [
                        'name' => 'New Caledonia',
                        'pl_name' => 'Nowa Kaledonia',
                        'code' => 'NC',
                        'currency' => 'CFP franc',
                        'currency_symbol' => '₣',
                        'currency_code' => 'XPF',
                    ],
                    [
                        'name' => 'Vanuatu',
                        'pl_name' => 'Vanuatu',
                        'code' => 'VU',
                        'currency' => 'Vanuatu vatu',
                        'currency_symbol' => 'Vt',
                        'currency_code' => 'VUV',
                    ],
                    [
                        'name' => 'Saint Helena, Ascension and Tristan da Cunha',
                        'pl_name' => 'Wyspa Świętej Heleny, Wyspa Wniebowstąpienia i Tristan da Cunha',
                        'code' => 'SH',
                        'currency' => 'Pound sterling',
                        'currency_symbol' => '£',
                        'currency_code' => 'GBP',
                    ],
                    [
                        'name' => 'Togo',
                        'pl_name' => 'Togo',
                        'code' => 'TG',
                        'currency' => 'West African CFA franc',
                        'currency_symbol' => 'Fr',
                        'currency_code' => 'XOF',
                    ],
                    [
                        'name' => 'British Virgin Islands',
                        'pl_name' => 'Brytyjskie Wyspy Dziewicze',
                        'code' => 'VG',
                        'currency' => 'United States dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'USD',
                    ],
                    [
                        'name' => 'Kenya',
                        'pl_name' => 'Kenia',
                        'code' => 'KE',
                        'currency' => 'Kenyan shilling',
                        'currency_symbol' => 'Sh',
                        'currency_code' => 'KES',
                    ],
                    [
                        'name' => 'Niue',
                        'pl_name' => 'Niue',
                        'code' => 'NU',
                        'currency' => 'New Zealand dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'NZD',
                    ],
                    [
                        'name' => 'Rwanda',
                        'pl_name' => 'Rwanda',
                        'code' => 'RW',
                        'currency' => 'Rwandan franc',
                        'currency_symbol' => 'Fr',
                        'currency_code' => 'RWF',
                    ],
                    [
                        'name' => 'Estonia',
                        'pl_name' => 'Estonia',
                        'code' => 'EE',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Romania',
                        'pl_name' => 'Rumunia',
                        'code' => 'RO',
                        'currency' => 'Romanian leu',
                        'currency_symbol' => 'lei',
                        'currency_code' => 'RON',
                    ],
                    [
                        'name' => 'Trinidad and Tobago',
                        'pl_name' => 'Trynidad i Tobago',
                        'code' => 'TT',
                        'currency' => 'Trinidad and Tobago dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'TTD',
                    ],
                    [
                        'name' => 'Guyana',
                        'pl_name' => 'Gujana',
                        'code' => 'GY',
                        'currency' => 'Guyanese dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'GYD',
                    ],
                    [
                        'name' => 'Timor-Leste',
                        'pl_name' => 'Timor Wschodni',
                        'code' => 'TL',
                        'currency' => 'United States dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'USD',
                    ],
                    [
                        'name' => 'Vietnam',
                        'pl_name' => 'Wietnam',
                        'code' => 'VN',
                        'currency' => 'Vietnamese đồng',
                        'currency_symbol' => '₫',
                        'currency_code' => 'VND',
                    ],
                    [
                        'name' => 'Uruguay',
                        'pl_name' => 'Urugwaj',
                        'code' => 'UY',
                        'currency' => 'Uruguayan peso',
                        'currency_symbol' => '$',
                        'currency_code' => 'UYU',
                    ],
                    [
                        'name' => 'Vatican City',
                        'pl_name' => 'Watykan',
                        'code' => 'VA',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Hong Kong',
                        'pl_name' => 'Hongkong',
                        'code' => 'HK',
                        'currency' => 'Hong Kong dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'HKD',
                    ],
                    [
                        'name' => 'Austria',
                        'pl_name' => 'Austria',
                        'code' => 'AT',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Antigua and Barbuda',
                        'pl_name' => 'Antigua i Barbuda',
                        'code' => 'AG',
                        'currency' => 'Eastern Caribbean dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'XCD',
                    ],
                    [
                        'name' => 'Turkmenistan',
                        'pl_name' => 'Turkmenistan',
                        'code' => 'TM',
                        'currency' => 'Turkmenistan manat',
                        'currency_symbol' => 'm',
                        'currency_code' => 'TMT',
                    ],
                    [
                        'name' => 'Mozambique',
                        'pl_name' => 'Mozambik',
                        'code' => 'MZ',
                        'currency' => 'Mozambican metical',
                        'currency_symbol' => 'MT',
                        'currency_code' => 'MZN',
                    ],
                    [
                        'name' => 'Panama',
                        'pl_name' => 'Panama',
                        'code' => 'PA',
                        'currency' => 'Panamanian balboa',
                        'currency_symbol' => 'B/.',
                        'currency_code' => 'PAB',
                    ],
                    [
                        'name' => 'Micronesia',
                        'pl_name' => 'Mikronezja',
                        'code' => 'FM',
                        'currency' => 'United States dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'USD',
                    ],
                    [
                        'name' => 'Ireland',
                        'pl_name' => 'Irlandia',
                        'code' => 'IE',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Curaçao',
                        'pl_name' => 'Curaçao',
                        'code' => 'CW',
                        'currency' => 'Netherlands Antillean guilder',
                        'currency_symbol' => 'ƒ',
                        'currency_code' => 'ANG',
                    ],
                    [
                        'name' => 'French Guiana',
                        'pl_name' => 'Gujana Francuska',
                        'code' => 'GF',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Norway',
                        'pl_name' => 'Norwegia',
                        'code' => 'NO',
                        'currency' => 'Norwegian krone',
                        'currency_symbol' => 'kr',
                        'currency_code' => 'NOK',
                    ],
                    [
                        'name' => 'Åland Islands',
                        'pl_name' => 'Wyspy Alandzkie',
                        'code' => 'AX',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Central African Republic',
                        'pl_name' => 'Republika Środkowoafrykańska',
                        'code' => 'CF',
                        'currency' => 'Central African CFA franc',
                        'currency_symbol' => 'Fr',
                        'currency_code' => 'XAF',
                    ],
                    [
                        'name' => 'Burkina Faso',
                        'pl_name' => 'Burkina Faso',
                        'code' => 'BF',
                        'currency' => 'West African CFA franc',
                        'currency_symbol' => 'Fr',
                        'currency_code' => 'XOF',
                    ],
                    [
                        'name' => 'Eritrea',
                        'pl_name' => 'Erytrea',
                        'code' => 'ER',
                        'currency' => 'Eritrean nakfa',
                        'currency_symbol' => 'Nfk',
                        'currency_code' => 'ERN',
                    ],
                    [
                        'name' => 'Tanzania',
                        'pl_name' => 'Tanzania',
                        'code' => 'TZ',
                        'currency' => 'Tanzanian shilling',
                        'currency_symbol' => 'Sh',
                        'currency_code' => 'TZS',
                    ],
                    [
                        'name' => 'South Korea',
                        'pl_name' => 'Korea Południowa',
                        'code' => 'KR',
                        'currency' => 'South Korean won',
                        'currency_symbol' => '₩',
                        'currency_code' => 'KRW',
                    ],
                    [
                        'name' => 'Jordan',
                        'pl_name' => 'Jordania',
                        'code' => 'JO',
                        'currency' => 'Jordanian dinar',
                        'currency_symbol' => 'د.ا',
                        'currency_code' => 'JOD',
                    ],
                    [
                        'name' => 'Mauritania',
                        'pl_name' => 'Mauretania',
                        'code' => 'MR',
                        'currency' => 'Mauritanian ouguiya',
                        'currency_symbol' => 'UM',
                        'currency_code' => 'MRU',
                    ],
                    [
                        'name' => 'Lithuania',
                        'pl_name' => 'Litwa',
                        'code' => 'LT',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'United States Minor Outlying Islands',
                        'pl_name' => 'Dalekie Wyspy Mniejsze Stanów Zjednoczonych',
                        'code' => 'UM',
                        'currency' => 'United States dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'USD',
                    ],
                    [
                        'name' => 'Slovakia',
                        'pl_name' => 'Słowacja',
                        'code' => 'SK',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Angola',
                        'pl_name' => 'Angola',
                        'code' => 'AO',
                        'currency' => 'Angolan kwanza',
                        'currency_symbol' => 'Kz',
                        'currency_code' => 'AOA',
                    ],
                    [
                        'name' => 'Kazakhstan',
                        'pl_name' => 'Kazachstan',
                        'code' => 'KZ',
                        'currency' => 'Kazakhstani tenge',
                        'currency_symbol' => '₸',
                        'currency_code' => 'KZT',
                    ],
                    [
                        'name' => 'Moldova',
                        'pl_name' => 'Mołdawia',
                        'code' => 'MD',
                        'currency' => 'Moldovan leu',
                        'currency_symbol' => 'L',
                        'currency_code' => 'MDL',
                    ],
                    [
                        'name' => 'Mali',
                        'pl_name' => 'Mali',
                        'code' => 'ML',
                        'currency' => 'West African CFA franc',
                        'currency_symbol' => 'Fr',
                        'currency_code' => 'XOF',
                    ],
                    [
                        'name' => 'Falkland Islands',
                        'pl_name' => 'Falklandy',
                        'code' => 'FK',
                        'currency' => 'Falkland Islands pound',
                        'currency_symbol' => '£',
                        'currency_code' => 'FKP',
                    ],
                    [
                        'name' => 'Armenia',
                        'pl_name' => 'Armenia',
                        'code' => 'AM',
                        'currency' => 'Armenian dram',
                        'currency_symbol' => '֏',
                        'currency_code' => 'AMD',
                    ],
                    [
                        'name' => 'Samoa',
                        'pl_name' => 'Samoa',
                        'code' => 'WS',
                        'currency' => 'Samoan tālā',
                        'currency_symbol' => 'T',
                        'currency_code' => 'WST',
                    ],
                    [
                        'name' => 'Jersey',
                        'pl_name' => 'Jersey',
                        'code' => 'JE',
                        'currency' => 'British pound',
                        'currency_symbol' => '£',
                        'currency_code' => 'GBP',
                    ],
                    [
                        'name' => 'Japan',
                        'pl_name' => 'Japonia',
                        'code' => 'JP',
                        'currency' => 'Japanese yen',
                        'currency_symbol' => '¥',
                        'currency_code' => 'JPY',
                    ],
                    [
                        'name' => 'Bolivia',
                        'pl_name' => 'Boliwia',
                        'code' => 'BO',
                        'currency' => 'Bolivian boliviano',
                        'currency_symbol' => 'Bs.',
                        'currency_code' => 'BOB',
                    ],
                    [
                        'name' => 'Chile',
                        'pl_name' => 'Chile',
                        'code' => 'CL',
                        'currency' => 'Chilean peso',
                        'currency_symbol' => '$',
                        'currency_code' => 'CLP',
                    ],
                    [
                        'name' => 'United States',
                        'pl_name' => 'Stany Zjednoczone',
                        'code' => 'US',
                        'currency' => 'United States dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'USD',
                    ],
                    [
                        'name' => 'Saint Vincent and the Grenadines',
                        'pl_name' => 'Saint Vincent i Grenadyny',
                        'code' => 'VC',
                        'currency' => 'Eastern Caribbean dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'XCD',
                    ],
                    [
                        'name' => 'Bermuda',
                        'pl_name' => 'Bermudy',
                        'code' => 'BM',
                        'currency' => 'Bermudian dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'BMD',
                    ],
                    [
                        'name' => 'Seychelles',
                        'pl_name' => 'Seszele',
                        'code' => 'SC',
                        'currency' => 'Seychellois rupee',
                        'currency_symbol' => '₨',
                        'currency_code' => 'SCR',
                    ],
                    [
                        'name' => 'British Indian Ocean Territory',
                        'pl_name' => 'Brytyjskie Terytorium Oceanu Indyjskiego',
                        'code' => 'IO',
                        'currency' => 'United States dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'USD',
                    ],
                    [
                        'name' => 'Guatemala',
                        'pl_name' => 'Gwatemala',
                        'code' => 'GT',
                        'currency' => 'Guatemalan quetzal',
                        'currency_symbol' => 'Q',
                        'currency_code' => 'GTQ',
                    ],
                    [
                        'name' => 'Ecuador',
                        'pl_name' => 'Ekwador',
                        'code' => 'EC',
                        'currency' => 'United States dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'USD',
                    ],
                    [
                        'name' => 'Martinique',
                        'pl_name' => 'Martynika',
                        'code' => 'MQ',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Tajikistan',
                        'pl_name' => 'Tadżykistan',
                        'code' => 'TJ',
                        'currency' => 'Tajikistani somoni',
                        'currency_symbol' => 'ЅМ',
                        'currency_code' => 'TJS',
                    ],
                    [
                        'name' => 'Malta',
                        'pl_name' => 'Malta',
                        'code' => 'MT',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Gambia',
                        'pl_name' => 'Gambia',
                        'code' => 'GM',
                        'currency' => 'dalasi',
                        'currency_symbol' => 'D',
                        'currency_code' => 'GMD',
                    ],
                    [
                        'name' => 'Nigeria',
                        'pl_name' => 'Nigeria',
                        'code' => 'NG',
                        'currency' => 'Nigerian naira',
                        'currency_symbol' => '₦',
                        'currency_code' => 'NGN',
                    ],
                    [
                        'name' => 'Bahamas',
                        'pl_name' => 'Bahamy',
                        'code' => 'BS',
                        'currency' => 'Bahamian dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'BSD',
                    ],
                    [
                        'name' => 'Kosovo',
                        'pl_name' => 'Kosowo',
                        'code' => 'XK',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Kuwait',
                        'pl_name' => 'Kuwejt',
                        'code' => 'KW',
                        'currency' => 'Kuwaiti dinar',
                        'currency_symbol' => 'د.ك',
                        'currency_code' => 'KWD',
                    ],
                    [
                        'name' => 'Maldives',
                        'pl_name' => 'Malediwy',
                        'code' => 'MV',
                        'currency' => 'Maldivian rufiyaa',
                        'currency_symbol' => '.ރ',
                        'currency_code' => 'MVR',
                    ],
                    [
                        'name' => 'South Sudan',
                        'pl_name' => 'Sudan',
                        'code' => 'SS',
                        'currency' => 'South Sudanese pound',
                        'currency_symbol' => '£',
                        'currency_code' => 'SSP',
                    ],
                    [
                        'name' => 'Iran',
                        'pl_name' => 'Iran',
                        'code' => 'IR',
                        'currency' => 'Iranian rial',
                        'currency_symbol' => '﷼',
                        'currency_code' => 'IRR',
                    ],
                    [
                        'name' => 'Albania',
                        'pl_name' => 'Albania',
                        'code' => 'AL',
                        'currency' => 'Albanian lek',
                        'currency_symbol' => 'L',
                        'currency_code' => 'ALL',
                    ],
                    [
                        'name' => 'Brazil',
                        'pl_name' => 'Brazylia',
                        'code' => 'BR',
                        'currency' => 'Brazilian real',
                        'currency_symbol' => 'R$',
                        'currency_code' => 'BRL',
                    ],
                    [
                        'name' => 'Serbia',
                        'pl_name' => 'Serbia',
                        'code' => 'RS',
                        'currency' => 'Serbian dinar',
                        'currency_symbol' => 'дин.',
                        'currency_code' => 'RSD',
                    ],
                    [
                        'name' => 'Belize',
                        'pl_name' => 'Belize',
                        'code' => 'BZ',
                        'currency' => 'Belize dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'BZD',
                    ],
                    [
                        'name' => 'Myanmar',
                        'pl_name' => 'Mjanma',
                        'code' => 'MM',
                        'currency' => 'Burmese kyat',
                        'currency_symbol' => 'Ks',
                        'currency_code' => 'MMK',
                    ],
                    [
                        'name' => 'Bhutan',
                        'pl_name' => 'Bhutan',
                        'code' => 'BT',
                        'currency' => 'Bhutanese ngultrum',
                        'currency_symbol' => 'Nu.',
                        'currency_code' => 'BTN',
                    ],
                    [
                        'name' => 'Venezuela',
                        'pl_name' => 'Wenezuela',
                        'code' => 'VE',
                        'currency' => 'Venezuelan bolívar soberano',
                        'currency_symbol' => 'Bs.S.',
                        'currency_code' => 'VES',
                    ],
                    [
                        'name' => 'Liberia',
                        'pl_name' => 'Liberia',
                        'code' => 'LR',
                        'currency' => 'Liberian dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'LRD',
                    ],
                    [
                        'name' => 'Jamaica',
                        'pl_name' => 'Jamajka',
                        'code' => 'JM',
                        'currency' => 'Jamaican dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'JMD',
                    ],
                    [
                        'name' => 'Poland',
                        'pl_name' => 'Polska',
                        'code' => 'PL',
                        'currency' => 'Polish złoty',
                        'currency_symbol' => 'zł',
                        'currency_code' => 'PLN',
                    ],
                    [
                        'name' => 'Cayman Islands',
                        'pl_name' => 'Kajmany',
                        'code' => 'KY',
                        'currency' => 'Cayman Islands dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'KYD',
                    ],
                    [
                        'name' => 'Brunei',
                        'pl_name' => 'Brunei',
                        'code' => 'BN',
                        'currency' => 'Brunei dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'BND',
                    ],
                    [
                        'name' => 'Comoros',
                        'pl_name' => 'Komory',
                        'code' => 'KM',
                        'currency' => 'Comorian franc',
                        'currency_symbol' => 'Fr',
                        'currency_code' => 'KMF',
                    ],
                    [
                        'name' => 'Guam',
                        'pl_name' => 'Guam',
                        'code' => 'GU',
                        'currency' => 'United States dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'USD',
                    ],
                    [
                        'name' => 'Tonga',
                        'pl_name' => 'Tonga',
                        'code' => 'TO',
                        'currency' => 'Tongan paʻanga',
                        'currency_symbol' => 'T$',
                        'currency_code' => 'TOP',
                    ],
                    [
                        'name' => 'Kiribati',
                        'pl_name' => 'Kiribati',
                        'code' => 'KI',
                        'currency' => 'Australian dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'AUD',
                    ],
                    [
                        'name' => 'Ghana',
                        'pl_name' => 'Ghana',
                        'code' => 'GH',
                        'currency' => 'Ghanaian cedi',
                        'currency_symbol' => '₵',
                        'currency_code' => 'GHS',
                    ],
                    [
                        'name' => 'Chad',
                        'pl_name' => 'Czad',
                        'code' => 'TD',
                        'currency' => 'Central African CFA franc',
                        'currency_symbol' => 'Fr',
                        'currency_code' => 'XAF',
                    ],
                    [
                        'name' => 'Zimbabwe',
                        'pl_name' => 'Zimbabwe',
                        'code' => 'ZW',
                        'currency' => 'Zimbabwean dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'ZWL',
                    ],
                    [
                        'name' => 'Saint Martin',
                        'pl_name' => 'Saint-Martin',
                        'code' => 'MF',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Mongolia',
                        'pl_name' => 'Mongolia',
                        'code' => 'MN',
                        'currency' => 'Mongolian tögrög',
                        'currency_symbol' => '₮',
                        'currency_code' => 'MNT',
                    ],
                    [
                        'name' => 'Portugal',
                        'pl_name' => 'Portugalia',
                        'code' => 'PT',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'American Samoa',
                        'pl_name' => 'Samoa Amerykańskie',
                        'code' => 'AS',
                        'currency' => 'United States dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'USD',
                    ],
                    [
                        'name' => 'Republic of the Congo',
                        'pl_name' => 'Kongo',
                        'code' => 'CG',
                        'currency' => 'Central African CFA franc',
                        'currency_symbol' => 'Fr',
                        'currency_code' => 'XAF',
                    ],
                    [
                        'name' => 'Belgium',
                        'pl_name' => 'Belgia',
                        'code' => 'BE',
                        'currency' => 'Euro',
                        'currency_symbol' => '€',
                        'currency_code' => 'EUR',
                    ],
                    [
                        'name' => 'Israel',
                        'pl_name' => 'Izrael',
                        'code' => 'IL',
                        'currency' => 'Israeli new shekel',
                        'currency_symbol' => '₪',
                        'currency_code' => 'ILS',
                    ],
                    [
                        'name' => 'New Zealand',
                        'pl_name' => 'Nowa Zelandia',
                        'code' => 'NZ',
                        'currency' => 'New Zealand dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'NZD',
                    ],
                    [
                        'name' => 'Nicaragua',
                        'pl_name' => 'Nikaragua',
                        'code' => 'NI',
                        'currency' => 'Nicaraguan córdoba',
                        'currency_symbol' => 'C$',
                        'currency_code' => 'NIO',
                    ],
                    [
                        'name' => 'Anguilla',
                        'pl_name' => 'Anguilla',
                        'code' => 'AI',
                        'currency' => 'Eastern Caribbean dollar',
                        'currency_symbol' => '$',
                        'currency_code' => 'XCD',
                    ],
                ]
            );

        }
    }
}
